export const CREATE_COURSE = "CREATE_COURSE";
export const LOAD_COURSES = "LOAD_COURSES";
export const LOAD_AUTHORS = "LOAD_AUTHORS";
export const SAVE_COURSE = "SAVE_COURSE";
export const UPDATE_COURSE = "UPDATE_COURSES";
